CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE (DNI IN NUMBER, NOMBRES IN VARCHAR2, 
                                              APELLIDO_PATERNO IN VARCHAR2, APELLIDO_MATERNO IN VARCHAR2, TELEFONO IN VARCHAR2, DIRECCION IN VARCHAR2)
AS 
BEGIN 
    INSERT INTO CLIENTE(DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
    VALUES(DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION);
END;


-----------------------------------------
create or replace TRIGGER CLIENTE_TRI
    BEFORE INSERT ON CLIENTE
        FOR EACH ROW
    BEGIN 
      SELECT CLIENTE_SEQ.NEXTVAL
      INTO :NEW.ID_CLIENTE
    FROM DUAL;
END;





CREATE OR REPLACE PROCEDURE ACTUALIZAR_CLIENTE(ID_CLIENTE IN NUMBER, DNI IN NUMBER, NOMBRES IN VARCHAR2, APELLIDO_PATERNO IN VARCHAR2, 
                                               APELLIDO_MATERNO IN VARCHAR2, TELEFONO IN VARCHAR2, DIRECCION IN VARCHAR2)
                                               
AS

    V_ID_CLIENTE NUMBER(4) := ID_CLIENTE;
    V_DNI NUMBER(8) := DNI;
    V_NOMBRES VARCHAR2(40) := NOMBRES;
    V_APELLIDO_PATERNO VARCHAR2(20) := APELLIDO_PATERNO;
    V_APELLIDO_MATERNO VARCHAR2(20) := APELLIDO_MATERNO;
    V_TELEFONO VARCHAR2(10) := TELEFONO;
    V_DIRECCION VARCHAR2(40) := DIRECCION;

BEGIN 
UPDATE CLIENTE SET DNI = V_DNI, NOMBRES = V_NOMBRES, APELLIDO_PATERNO = V_APELLIDO_PATERNO, APELLIDO_MATERNO = V_APELLIDO_MATERNO, 
                                          TELEFONO = V_TELEFONO, DIRECCION = V_DIRECCION WHERE ID_CLIENTE = V_ID_CLIENTE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
NULL;
WHEN OTHERS THEN
RAISE;
END ACTUALIZAR_CLIENTE;
    
    
    
CREATE OR REPLACE PROCEDURE ELIMINAR_CLIENTE(ID_CLIENTE IN NUMBER)
AS
    V_ID_CLIENTE NUMBER(4) := ID_CLIENTE;
BEGIN
DELETE FROM CLIENTE WHERE ID_CLIENTE = V_ID_CLIENTE;
END;
    
    
    
    
    
    
  CREATE SEQUENCE CLIENTE_SEQ START WITH 6;
    
    
    
    
    
                                               
                                               
                                               
                                               