CREATE TABLE CLIENTE(
    ID_CLIENTE           NUMBER(4),
    DNI                  NUMBER(8),
    NOMBRES             varchar2(40),
    APELLIDO_PATERNO    varchar2(20),
    APELLIDO_MATERNO    varchar2(20),
    TELEFONO            varchar2(10),
    DIRECCION           varchar2(40),
    
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);


CREATE TABLE ESTADO(
    
    ID_ESTADO 		NUMBER(4),
    FECHA_INICIO 	VARCHAR2(20),
    FECHA_FIN 		VARCHAR2(20),
    ESTADO 		VARCHAR2(40),
    CONSTRAINT ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)

);


CREATE TABLE CARGO(
    ID_CARGO            NUMBER(4),
    NOMBRE              varchar2(40),
    SUELDO              NUMBER(4),
    
    CONSTRAINT CARGO_PK PRIMARY KEY (ID_CARGO)
);




CREATE TABLE CATEGORIA(
    ID_CATEGORIA        NUMBER(4),
    NOMBRE              varchar2(40),
    DESCRIPCION         varchar(40),
    
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)
);




CREATE TABLE MUEBLE(
    ID_MUEBLE           NUMBER(4),
    NOMBRE              VARCHAR2(80),
    DESCRIPCION         varchar2(80),
    ID_CATEGORIA        NUMBER(4),
    
    CONSTRAINT MUEBLE_PK PRIMARY KEY (ID_MUEBLE),
    CONSTRAINT CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);




CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR        NUMBER(4),
    NOMBRE_EMPRESA      varchar2(40),
    TELEFONO_EMPRESA    varchar2(10),
    DIRECCION_EMPRESA   varchar2(40),
    
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR)
);



CREATE TABLE EMPLEADO(
    ID_EMPLEADO         NUMBER(4),
    DNI                 NUMBER(8),
    NOMBRES             varchar2(40),
    APELLIDO_PATERNO    varchar2(20),
    APELLIDO_MATERNO    varchar2(20),
    TELEFONO            varchar2(10),
    SEXO                varchar2(10),
    ID_CARGO            NUMBER(4),
    ID_ESTADO 		NUMBER(4),
    
    CONSTRAINT EMPLEADO_PK  PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT CARGO_FK     FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    CONSTRAINT ID_ESTADO_FK     FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);




CREATE TABLE PEDIDO_CLIENTE(
    ID_PEDIDO_CLIENTE       NUMBER(4),
    FECHA                   VARCHAR2(25),
    ID_CLIENTE              NUMBER(4),
    ID_EMPLEADO             NUMBER(4),
    
    CONSTRAINT PEDIDO_CLIENTE_PK    PRIMARY KEY (ID_PEDIDO_CLIENTE),
    CONSTRAINT CLIENTE_FK1          FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT EMPLEADO_FK1         FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);



CREATE TABLE PEDIDO_PROVEEDOR(
    ID_PEDIDO_PROVEEDOR     NUMBER(4),
    FECHA                   VARCHAR2(25),
    ID_PROVEEDOR            NUMBER(4),
    ID_EMPLEADO             NUMBER(4),
    
    CONSTRAINT PEDIDO_PROVEEDOR_PK  PRIMARY KEY (ID_PEDIDO_PROVEEDOR),
    CONSTRAINT PROVEEDOR_FK         FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    CONSTRAINT EMPLEADO_FK          FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);


CREATE TABLE DETALLE_PEDIDO_PROVEEDOR(
    ID_DETALLE_PEDIDO_PROVEEDOR     NUMBER(4),
    NOMBRE_PRODUCTO                 varchar2(25),
    CANTIDAD                        NUMBER(6),
    ID_PEDIDO_PROVEEDOR             NUMBER(4),
    
    CONSTRAINT DETALLE_PEDIDO_PROVEEDOR_PK  PRIMARY KEY (ID_DETALLE_PEDIDO_PROVEEDOR),
    CONSTRAINT PEDIDO_PROVEEDOR_FK     FOREIGN KEY (ID_PEDIDO_PROVEEDOR) REFERENCES PEDIDO_PROVEEDOR(ID_PEDIDO_PROVEEDOR)
);


CREATE TABLE DETALLE_PEDIDO_CLIENTE(
    ID_DETALLE_PEDIDO_CLIENTE       NUMBER(4),
    CANTIDAD                        NUMBER(6),
    ID_PEDIDO_CLIENTE               NUMBER(4),
    ID_MUEBLE                       NUMBER(4),
        
    CONSTRAINT DETALLE_PEDIDO_CLIENTE_PK    PRIMARY KEY (ID_DETALLE_PEDIDO_CLIENTE),
    CONSTRAINT PEDIDO_CLIENTE_FK            FOREIGN KEY (ID_PEDIDO_CLIENTE) REFERENCES PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE),
    CONSTRAINT MUEBLE_FK                    FOREIGN KEY (ID_MUEBLE) REFERENCES MUEBLE(ID_MUEBLE)
);


CREATE TABLE ENVIO(
	ID_ENVIO                        NUMBER(4), 
	AGENCIA_ENVIO                   VARCHAR2(50),
    ID_DETALLE_PEDIDO_CLIENTE       NUMBER(4),
    ID_CLIENTE                      NUMBER(4),
    
    CONSTRAINT ENVIO_PK   PRIMARY KEY (ID_ENVIO),
    CONSTRAINT DETALLE_PEDIDO_CLIENTE_FK    FOREIGN KEY (ID_DETALLE_PEDIDO_CLIENTE) REFERENCES DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE),
    CONSTRAINT CLIENTE_FK    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
 );
 

CREATE TABLE DETALLE_ENVIO(
	ID_DETALLE_ENVIO                 NUMBER(4),
	DESCRIPCION                      VARCHAR2(100),
	DEPARTAMENTO                     VARCHAR2(50),
	PROVINCIA                        VARCHAR2(50),
    ID_ENVIO                         NUMBER(4),
    
    CONSTRAINT DETALLE_ENVIO_PK     PRIMARY KEY (ID_DETALLE_ENVIO),
	CONSTRAINT ENVIO_FK             FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);


CREATE TABLE INVENTARIO(
	ID_INVENTARIO                   NUMBER(4),
	STOCK                           NUMBER(4),
    ID_MUEBLE                       NUMBER(4),
    
    CONSTRAINT INVENTARIO_PK   PRIMARY KEY (ID_INVENTARIO),
	CONSTRAINT MUEBLES_FK    FOREIGN KEY (ID_MUEBLE) REFERENCES MUEBLE(ID_MUEBLE)
);


CREATE TABLE DETALLE_PAGO(
    ID_DETALLE_PAGO                 NUMBER(4),
    TIPO_DE_PAGO                    VARCHAR2(40),
    ID_DETALLE_PEDIDO_CLIENTE       NUMBER(4),
        
    CONSTRAINT DETALLE_PAGO_PK              PRIMARY KEY (ID_DETALLE_PAGO),
    CONSTRAINT DETALLES_PEDIDOS_CLIENTES_FK    FOREIGN KEY (ID_DETALLE_PEDIDO_CLIENTE) REFERENCES DETALLE_PEDIDO_CLIENTE (ID_DETALLE_PEDIDO_CLIENTE )
); 


CREATE TABLE PERSONA(
    ID_PERSONA                      NUMBER(4),
    ID_CLIENTE                      NUMBER(4),
    ID_EMPLEADO                     NUMBER(4),
    
    CONSTRAINT PERSONA PRIMARY KEY (ID_PERSONA),
    CONSTRAINT CLIENTES_FK    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT EMPLEADOS_FK   FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE FACTURA(
    ID_FACTURA                      NUMBER(4),
    SUBTOTAL                        NUMBER(6),
    IGV                             NUMBER(6),
    TOTAL                           NUMBER(6),
    ID_DETALLE_PAGO                 NUMBER(4),
        
    CONSTRAINT FACTURA_PK           PRIMARY KEY (ID_FACTURA),
    CONSTRAINT DETALLE_PAGO_FK      FOREIGN KEY (ID_DETALLE_PAGO) REFERENCES DETALLE_PAGO(ID_DETALLE_PAGO)
);



CREATE TABLE BOLETA(
    ID_BOLETA                       NUMBER(4),
    IMPORTE                         NUMBER(6),
    ID_DETALLE_PAGO                 NUMBER(4),
        
    CONSTRAINT BOLETA_PK          PRIMARY KEY (ID_BOLETA),
    CONSTRAINT DETALLE_PAGO_FK2   FOREIGN KEY (ID_DETALLE_PAGO) REFERENCES DETALLE_PAGO(ID_DETALLE_PAGO)
);


CREATE TABLE DETALLE_FACTURA(
    ID_DETALLE_FACTURA              NUMBER(4),
    CANTIDAD                        NUMBER(4),
    DESCRIPCION                     VARCHAR2(40),
    PRECIO_UNITARIO                 NUMBER(6),
    ID_FACTURA                      NUMBER(4),
        
    CONSTRAINT DETALLE_FACTURA_PK PRIMARY KEY (ID_DETALLE_FACTURA),
    CONSTRAINT FACTURA_FK         FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);




CREATE TABLE DETALLE_BOLETA(
    ID_DETALLE_BOLETA               NUMBER(4),
    CANTIDAD                        NUMBER(4),
    DESCRIPCION                     VARCHAR2(40),
    PRECIO_UNITARIO                 NUMBER(6),
    ID_BOLETA                       NUMBER(4),
        
    CONSTRAINT DETALLE_BOLETA_PK  PRIMARY KEY (ID_DETALLE_BOLETA),
    CONSTRAINT BOLETA_FK          FOREIGN KEY (ID_BOLETA) REFERENCES BOLETA(ID_BOLETA)
);


---- USUARIOS

CREATE TABLE USUARIO(
  ID                NUMBER(4) PRIMARY KEY,
  NOMBRE_USUARIO    VARCHAR2(25),
  CONTRASEÑA        VARCHAR2(25)
);


--- DATOS USUARIOS
INSERT INTO USUARIO(ID, NOMBRE_USUARIO, CONTRASEÑA)
VALUES(1, 'anthony', '12345');

INSERT INTO USUARIO(ID, NOMBRE_USUARIO, CONTRASEÑA)
VALUES(2, 'tabada', 'tabada');


-------------------------------------------------- INSERTS Y SECUENCIAS  ---------------------------------------------------------------------

--- SECUENCIA DE CLIENTE -----

CREATE SEQUENCE SEQ_ID_CLIENTE NOCYCLE;

INSERT INTO CLIENTE(ID_CLIENTE, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
VALUES(SEQ_ID_CLIENTE.NEXTVAL, 45120035, 'JUAN', 'PEREZ', 'CRUZ', '456215', 'LA ESPERANZA #123');

INSERT INTO CLIENTE(ID_CLIENTE, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
VALUES(SEQ_ID_CLIENTE.NEXTVAL, 50148956, 'MARIA', 'SANTIAGO', 'MENDEZ', '685014', 'EL MILAGRO #520');

INSERT INTO CLIENTE(ID_CLIENTE, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
VALUES(SEQ_ID_CLIENTE.NEXTVAL, 85124790, 'JOSE', 'CAYO', 'CRUZADO', '801254', 'AV. ESPAÑA #741');

INSERT INTO CLIENTE(ID_CLIENTE, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
VALUES(SEQ_ID_CLIENTE.NEXTVAL, 12840289, 'NIGUEL', 'VEGA', 'STING', '012512357', 'JR. PARURO #180');

INSERT INTO CLIENTE(ID_CLIENTE, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, DIRECCION)
VALUES(SEQ_ID_CLIENTE.NEXTVAL, 54709501, 'LIS', 'FERNAN', 'NILO', '5102474', 'CARLOS IZAGUIRRE #990');


----- SECUENCIA DE ESTADO-----

CREATE SEQUENCE SEQ_ID_ESTADO NOCYCLE;

INSERT INTO ESTADO(ID_ESTADO, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES(SEQ_ID_ESTADO.NEXTVAL, '20/03/2018', '20/03/2019', 'CON OPCION A RENOVAR');

INSERT INTO ESTADO(ID_ESTADO, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES(SEQ_ID_ESTADO.NEXTVAL, '20/03/2018', '20/03/2019', 'CON OPCION A RENOVAR');

INSERT INTO ESTADO(ID_ESTADO, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES(SEQ_ID_ESTADO.NEXTVAL, '21/03/2018', '21/03/2019', 'CON OPCION A RENOVAR');

INSERT INTO ESTADO(ID_ESTADO, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES(SEQ_ID_ESTADO.NEXTVAL, '21/03/2018', '21/03/2019', 'CON OPCION A RENOVAR');

INSERT INTO ESTADO(ID_ESTADO, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES(SEQ_ID_ESTADO.NEXTVAL, '22/03/2018', '22/03/2019', 'CON OPCION A RENOVAR');



------ SECUENCIA DE CARGO ------

CREATE SEQUENCE SEQ_ID_CARGO NOCYCLE;

INSERT INTO CARGO(ID_CARGO, NOMBRE, SUELDO) 
VALUES(SEQ_ID_CARGO.NEXTVAL, 'ADMINISTRADOR', 800);

INSERT INTO CARGO(ID_CARGO, NOMBRE, SUELDO) 
VALUES(SEQ_ID_CARGO.NEXTVAL, 'CORTADOR', 850);

INSERT INTO CARGO(ID_CARGO, NOMBRE, SUELDO)
VALUES(SEQ_ID_CARGO.NEXTVAL, 'LAQUEADOR', 850);



----- SECUENCIA DE  CATEGORIA

CREATE SEQUENCE SEQ_ID_CATEGORIA NOCYCLE;

INSERT INTO CATEGORIA(ID_CATEGORIA, NOMBRE, DESCRIPCION)
VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'MUEBLE', 'MUEBLE DE TRES CUERPOS');

INSERT INTO CATEGORIA(ID_CATEGORIA, NOMBRE, DESCRIPCION)
VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'CAMA', 'CAMA DE UNA PLAZA O DOS PLAZAS');

INSERT INTO CATEGORIA(ID_CATEGORIA, NOMBRE, DESCRIPCION)
VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'VELADOR', 'VELADOR DE 3 CAJONES');

INSERT INTO CATEGORIA(ID_CATEGORIA, NOMBRE, DESCRIPCION)
VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'ESTANTE', 'ESTANTE DE DOS PIZOS DE MADERA');



--- SECUENCIA DE MUEBLE

CREATE SEQUENCE SEQ_ID_MUEBLE NOCYCLE;

INSERT INTO MUEBLE(ID_MUEBLE, NOMBRE, DESCRIPCION, ID_CATEGORIA)
VALUES(SEQ_ID_MUEBLE.NEXTVAL, 'VELADOR', 'VELADOR DE DOS CAJONES DE MADERA CEDRO', 3);

INSERT INTO MUEBLE(ID_MUEBLE, NOMBRE, DESCRIPCION, ID_CATEGORIA)
VALUES(SEQ_ID_MUEBLE.NEXTVAL, 'CAMA', 'CAMA DE 2 PLAZAS', 2);

INSERT INTO MUEBLE(ID_MUEBLE, NOMBRE, DESCRIPCION, ID_CATEGORIA)
VALUES(SEQ_ID_MUEBLE.NEXTVAL, 'MUEBLE', 'MUEBLES DE TRES CUERPOS DE CUERO', 1);


---- PROVEEDOR

CREATE SEQUENCE SEQ_ID_PROVEEDOR NOCYCLE;

INSERT INTO PROVEEDOR(ID_PROVEEDOR, NOMBRE_EMPRESA, TELEFONO_EMPRESA, DIRECCION_EMPRESA)
VALUES(SEQ_ID_PROVEEDOR.NEXTVAL, 'MADERER', '451280', 'AV. AMERICA #500');

INSERT INTO PROVEEDOR(ID_PROVEEDOR, NOMBRE_EMPRESA, TELEFONO_EMPRESA, DIRECCION_EMPRESA)
VALUES(SEQ_ID_PROVEEDOR.NEXTVAL, 'PINTURA', '750158', 'AV.PERÚ #100');

INSERT INTO PROVEEDOR(ID_PROVEEDOR, NOMBRE_EMPRESA, TELEFONO_EMPRESA, DIRECCION_EMPRESA)
VALUES(SEQ_ID_PROVEEDOR.NEXTVAL, 'EL TORNILLO', '665710', 'AV. MANSICHE #890');

INSERT INTO PROVEEDOR(ID_PROVEEDOR, NOMBRE_EMPRESA, TELEFONO_EMPRESA, DIRECCION_EMPRESA)
VALUES(SEQ_ID_PROVEEDOR.NEXTVAL, 'TELAR', '421000', 'AV. ESPAÑA #601');



---------  EMPLEADO

CREATE SEQUENCE SEQ_ID_EMPLEADO NOCYCLE;

INSERT INTO EMPLEADO(ID_EMPLEADO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, SEXO, ID_CARGO, ID_ESTADO)
VALUES(SEQ_ID_EMPLEADO.NEXTVAL, 51075401, 'PEDRO', 'MENEZ', 'PEZ', '987456015', 'MASCULINO', 2, 1);

INSERT INTO EMPLEADO(ID_EMPLEADO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, SEXO, ID_CARGO, ID_ESTADO)
VALUES(SEQ_ID_EMPLEADO.NEXTVAL, 50100325 ,'JUAN', 'MEN', 'PEZAR', '941028123', 'MASCULINO', 3, 2);

INSERT INTO EMPLEADO(ID_EMPLEADO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, SEXO, ID_CARGO, ID_ESTADO)
VALUES(SEQ_ID_EMPLEADO.NEXTVAL, 96856602 ,'LUISA', 'YEP', 'PINEDO', '912340851', 'FEMENINO', 1, 3);

INSERT INTO EMPLEADO(ID_EMPLEADO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, SEXO, ID_CARGO, ID_ESTADO)
VALUES(SEQ_ID_EMPLEADO.NEXTVAL, 74102148 ,'JAIME', 'RIX', 'CASINO', '912007860', 'MASCULINO', 2, 4);

INSERT INTO EMPLEADO(ID_EMPLEADO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO, SEXO, ID_CARGO, ID_ESTADO)
VALUES(SEQ_ID_EMPLEADO.NEXTVAL, 76128000 , 'ROLANDO', 'PENERD', 'GALIN', '910027506', 'MASCULINO', 1, 5);



------ PEDIDO_CLIENTE

CREATE SEQUENCE SEQ_ID_PEDIDO_CLIENTE NOCYCLE;

INSERT INTO PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE, FECHA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PEDIDO_CLIENTE.NEXTVAL, '05/05/2018', 1, 3);

INSERT INTO PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE, FECHA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PEDIDO_CLIENTE.NEXTVAL, '05/05/2018', 2, 5);

INSERT INTO PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE, FECHA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PEDIDO_CLIENTE.NEXTVAL, '06/05/2018', 3, 3);

INSERT INTO PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE, FECHA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PEDIDO_CLIENTE.NEXTVAL, '07/05/2018', 4, 5);

INSERT INTO PEDIDO_CLIENTE(ID_PEDIDO_CLIENTE, FECHA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PEDIDO_CLIENTE.NEXTVAL, '07/05/2018', 5, 3);


------ PEDIDO_PROVEEDOR

CREATE SEQUENCE SEQ_PEDIDO_PROVEEDOR NOCYCLE;

INSERT INTO PEDIDO_PROVEEDOR(ID_PEDIDO_PROVEEDOR, FECHA, ID_PROVEEDOR, ID_EMPLEADO)
VALUES(SEQ_PEDIDO_PROVEEDOR.NEXTVAL, '05/05/2018', 1, 1);

INSERT INTO PEDIDO_PROVEEDOR(ID_PEDIDO_PROVEEDOR, FECHA, ID_PROVEEDOR, ID_EMPLEADO)
VALUES(SEQ_PEDIDO_PROVEEDOR.NEXTVAL, '05/05/2018', 3, 2);

INSERT INTO PEDIDO_PROVEEDOR(ID_PEDIDO_PROVEEDOR, FECHA, ID_PROVEEDOR, ID_EMPLEADO)
VALUES(SEQ_PEDIDO_PROVEEDOR.NEXTVAL, '05/05/2018', 4, 4);

INSERT INTO PEDIDO_PROVEEDOR(ID_PEDIDO_PROVEEDOR, FECHA, ID_PROVEEDOR, ID_EMPLEADO)
VALUES(SEQ_PEDIDO_PROVEEDOR.NEXTVAL, '06/05/2018', 2, 1);



----   DETALLE_PEDIDO_PROVEEDOR

CREATE SEQUENCE SEQ_DETALLE_PEDIDO_PROVEEDOR NOCYCLE;

INSERT INTO DETALLE_PEDIDO_PROVEEDOR(ID_DETALLE_PEDIDO_PROVEEDOR, NOMBRE_PRODUCTO, CANTIDAD, ID_PEDIDO_PROVEEDOR)
VALUES(SEQ_DETALLE_PEDIDO_PROVEEDOR.NEXTVAL, 'MADERA DE CEDRO', 3, 1);

INSERT INTO DETALLE_PEDIDO_PROVEEDOR(ID_DETALLE_PEDIDO_PROVEEDOR, NOMBRE_PRODUCTO, CANTIDAD, ID_PEDIDO_PROVEEDOR)
VALUES(SEQ_DETALLE_PEDIDO_PROVEEDOR.NEXTVAL, 'PINTURA MARRON', 5, 4);

INSERT INTO DETALLE_PEDIDO_PROVEEDOR(ID_DETALLE_PEDIDO_PROVEEDOR, NOMBRE_PRODUCTO, CANTIDAD, ID_PEDIDO_PROVEEDOR)
VALUES(SEQ_DETALLE_PEDIDO_PROVEEDOR.NEXTVAL, 'TORNILLOS ESTRELLA', 36, 2);

INSERT INTO DETALLE_PEDIDO_PROVEEDOR(ID_DETALLE_PEDIDO_PROVEEDOR, NOMBRE_PRODUCTO, CANTIDAD, ID_PEDIDO_PROVEEDOR)
VALUES(SEQ_DETALLE_PEDIDO_PROVEEDOR.NEXTVAL, 'TELA DE CEDA', 7, 3);



----- DETALLE_PEDIDO_CLIENTE

CREATE SEQUENCE SEQ_ID_DETALLE_PEDIDO_CLIENTE NOCYCLE;

INSERT INTO DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE, CANTIDAD, ID_PEDIDO_CLIENTE, ID_MUEBLE)
VALUES(SEQ_ID_DETALLE_PEDIDO_CLIENTE.NEXTVAL, 1, 1, 1);

INSERT INTO DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE, CANTIDAD, ID_PEDIDO_CLIENTE, ID_MUEBLE)
VALUES(SEQ_ID_DETALLE_PEDIDO_CLIENTE.NEXTVAL, 1, 2, 2);


INSERT INTO DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE, CANTIDAD, ID_PEDIDO_CLIENTE, ID_MUEBLE)
VALUES(SEQ_ID_DETALLE_PEDIDO_CLIENTE.NEXTVAL, 1, 3, 3);

INSERT INTO DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE, CANTIDAD, ID_PEDIDO_CLIENTE, ID_MUEBLE)
VALUES(SEQ_ID_DETALLE_PEDIDO_CLIENTE.NEXTVAL, 1, 4, 3);

INSERT INTO DETALLE_PEDIDO_CLIENTE(ID_DETALLE_PEDIDO_CLIENTE, CANTIDAD, ID_PEDIDO_CLIENTE, ID_MUEBLE)
VALUES(SEQ_ID_DETALLE_PEDIDO_CLIENTE.NEXTVAL, 1, 5, 1);



---- ENVIO

CREATE SEQUENCE SEQ_ID_ENVIO NOCYCLE;

INSERT INTO ENVIO(ID_ENVIO, AGENCIA_ENVIO, ID_DETALLE_PEDIDO_CLIENTE, ID_CLIENTE)
VALUES(SEQ_ID_ENVIO.NEXTVAL, 'EMTRAFESA', 4, 4);

INSERT INTO ENVIO(ID_ENVIO, AGENCIA_ENVIO, ID_DETALLE_PEDIDO_CLIENTE, ID_CLIENTE)
VALUES(SEQ_ID_ENVIO.NEXTVAL, 'CRUZ DEL SUR', 5, 5);


--- DETALLE_ENVIO

CREATE SEQUENCE SEQ_ID_DETALLE_ENVIO NOCYCLE;

INSERT INTO DETALLE_ENVIO(ID_DETALLE_ENVIO, DESCRIPCION, DEPARTAMENTO, PROVINCIA, ID_ENVIO)
VALUES(SEQ_ID_DETALLE_ENVIO.NEXTVAL, 'CAMA DE DOS PLAZAS', 'LIMA', 'CENTRO', 1);

INSERT INTO DETALLE_ENVIO(ID_DETALLE_ENVIO, DESCRIPCION, DEPARTAMENTO, PROVINCIA, ID_ENVIO)
VALUES(SEQ_ID_DETALLE_ENVIO.NEXTVAL, 'VELADOR DE DOS CAJONES DE MADERA CEDRO', 'LIMA', 'COMAS', 2);



---- INVENTARIO

CREATE SEQUENCE SEQ_ID_INVENTARIO NOCYCLE;

INSERT INTO INVENTARIO(ID_INVENTARIO, STOCK, ID_MUEBLE)
VALUES(SEQ_ID_INVENTARIO.NEXTVAL, 5, 1);

INSERT INTO INVENTARIO(ID_INVENTARIO, STOCK, ID_MUEBLE)
VALUES(SEQ_ID_INVENTARIO.NEXTVAL, 5, 2);

INSERT INTO INVENTARIO(ID_INVENTARIO, STOCK, ID_MUEBLE)
VALUES(SEQ_ID_INVENTARIO.NEXTVAL, 5, 3);



------ DETALLE_PAGO

CREATE SEQUENCE SEQ_ID_DETALLE_PAGO NOCYCLE;

INSERT INTO DETALLE_PAGO(ID_DETALLE_PAGO, TIPO_DE_PAGO, ID_DETALLE_PEDIDO_CLIENTE)
VALUES(SEQ_ID_DETALLE_PAGO.NEXTVAL, 'CONTADO', 1);

INSERT INTO DETALLE_PAGO(ID_DETALLE_PAGO, TIPO_DE_PAGO, ID_DETALLE_PEDIDO_CLIENTE)
VALUES(SEQ_ID_DETALLE_PAGO.NEXTVAL, 'CONTADO', 2);

INSERT INTO DETALLE_PAGO(ID_DETALLE_PAGO, TIPO_DE_PAGO, ID_DETALLE_PEDIDO_CLIENTE)
VALUES(SEQ_ID_DETALLE_PAGO.NEXTVAL, 'CONTADO', 3);

INSERT INTO DETALLE_PAGO(ID_DETALLE_PAGO, TIPO_DE_PAGO, ID_DETALLE_PEDIDO_CLIENTE)
VALUES(SEQ_ID_DETALLE_PAGO.NEXTVAL, 'DEPOSITO', 4);

INSERT INTO DETALLE_PAGO(ID_DETALLE_PAGO, TIPO_DE_PAGO, ID_DETALLE_PEDIDO_CLIENTE)
VALUES(SEQ_ID_DETALLE_PAGO.NEXTVAL, 'DEPOSITO', 5);


------ PERSONA

CREATE SEQUENCE SEQ_ID_PERSONA NOCYCLE;

INSERT INTO PERSONA(ID_PERSONA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PERSONA.NEXTVAL, 1, 1);

INSERT INTO PERSONA(ID_PERSONA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PERSONA.NEXTVAL, 2, 2);

INSERT INTO PERSONA(ID_PERSONA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PERSONA.NEXTVAL, 3, 3);

INSERT INTO PERSONA(ID_PERSONA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PERSONA.NEXTVAL, 4, 4);

INSERT INTO PERSONA(ID_PERSONA, ID_CLIENTE, ID_EMPLEADO)
VALUES(SEQ_ID_PERSONA.NEXTVAL, 5, 5);


----- FACTURA

CREATE SEQUENCE SEQ_ID_FACTURA NOCYCLE;

INSERT INTO FACTURA(ID_FACTURA, SUBTOTAL, IGV, TOTAL, ID_DETALLE_PAGO)
VALUES(SEQ_ID_FACTURA.NEXTVAL, 1107, 243, 1350, 3);

INSERT INTO FACTURA(ID_FACTURA, SUBTOTAL, IGV, TOTAL, ID_DETALLE_PAGO)
VALUES(SEQ_ID_FACTURA.NEXTVAL, 738, 162, 900, 1);


---- BOLETA

CREATE SEQUENCE SEQ_ID_BOLETA NOCYCLE;

INSERT INTO BOLETA(ID_BOLETA, IMPORTE, ID_DETALLE_PAGO)
VALUES(SEQ_ID_BOLETA.NEXTVAL, 900, 1);

INSERT INTO BOLETA(ID_BOLETA, IMPORTE, ID_DETALLE_PAGO)
VALUES(SEQ_ID_BOLETA.NEXTVAL, 800, 2);

INSERT INTO BOLETA(ID_BOLETA, IMPORTE, ID_DETALLE_PAGO)
VALUES(SEQ_ID_BOLETA.NEXTVAL, 1350, 3);


---- DETALLE_FACTURA
CREATE SEQUENCE SEQ_ID_DETALLE_FACTURA NOCYCLE;

INSERT INTO DETALLE_FACTURA(ID_DETALLE_FACTURA, CANTIDAD, DESCRIPCION, PRECIO_UNITARIO, ID_FACTURA)
VALUES(SEQ_ID_DETALLE_FACTURA.NEXTVAL, 1, 'MUEBLE DE 3 CUERPOS DE TELA', 1350, 1);

INSERT INTO DETALLE_FACTURA(ID_DETALLE_FACTURA, CANTIDAD, DESCRIPCION, PRECIO_UNITARIO, ID_FACTURA)
VALUES(SEQ_ID_DETALLE_FACTURA.NEXTVAL, 2, 'VELADORES DE MADERA DE CEDRO', 450, 2);


---- DETALLE_BOLETA


CREATE SEQUENCE SEQ_ID_DETALLE_BOLETA NOCYCLE;

INSERT INTO DETALLE_BOLETA(ID_DETALLE_BOLETA, CANTIDAD, DESCRIPCION, PRECIO_UNITARIO, ID_BOLETA)
VALUES(SEQ_ID_DETALLE_BOLETA.NEXTVAL, 2, 'VELADORES DE MADERA DE CEDRO', 450, 1);

INSERT INTO DETALLE_BOLETA(ID_DETALLE_BOLETA, CANTIDAD, DESCRIPCION, PRECIO_UNITARIO, ID_BOLETA)
VALUES(SEQ_ID_DETALLE_BOLETA.NEXTVAL, 1, 'CAMA DE DOS PLAZAS TORNILLO', 800, 2);

INSERT INTO DETALLE_BOLETA(ID_DETALLE_BOLETA, CANTIDAD, DESCRIPCION, PRECIO_UNITARIO, ID_BOLETA)
VALUES(SEQ_ID_DETALLE_BOLETA.NEXTVAL, 1, 'MUEBLE DE TRES CUERPOS DE TELA', 1350, 3);




---------- TRIGGERS



CREATE OR REPLACE
TRIGGER T_NUEVOS_DEPARTAMENTOS
AFTER INSERT ON DEPARTAMENTOS
BEGIN
DBMS_OUTPUT.PUT_LINE('Se acaban de registrar uno o más departamentos');
END T_NUEVOS_DEPARTAMENTOS;













